#server.port = 8081
#server.servlet.session.timeout=5
spring.session.timeout.seconds=300

#spring.mvc.static-path-pattern=/**
#lista vrednosti direktorijuma
#spring.resources.static-locations=

#spring.mvc.view.prefix: /WEB-INF/jsp/
#spring.mvc.view.suffix: .jsp

spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false


paths.baseResourcePath=src/main/resources/

server.servlet.contextPath=/PrviMavenVebProjekat

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}